from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent
IMG_DIR = ROOT_DIR / "img"

RADAR_ALCANCE = 3
QUANTIDADE_ESFERAS = 7
MARGEM_TELA = 18
MOVIMENTO_FPS = 15
MOVIMENTO_FPS_MIN = 1
MOVIMENTO_FPS_MAX = 30

TERRENO_DESCONHECIDO_PADRAO = 0
PENALIDADE_AGUA_PASSO = 8
PENALIDADE_MONTANHA_PASSO = 35
PENALIDADE_AGUA_DESTINO = 20
PENALIDADE_MONTANHA_DESTINO = 90

FATOR_ESCURECER_NAO_PERCORRIDO = 0.70
FATOR_ESCURECER_DETECTADO_RADAR = 0.99

AGENTE_IMAGEM_CAMINHO = str(IMG_DIR / "GokuPixel.png")
FUNDO_IMAGEM_CAMINHO = str(IMG_DIR / "goku3geminiMelhorada.jpg")
CASA_MESTRE_KAME_IMAGEM_CAMINHO = str(IMG_DIR / "mestrekame4.png")

# Exemplo: MANUAL_ESFERAS = [(5, 3), (10, 8)]
MANUAL_ESFERAS: list[tuple[int, int]] = [
   # (0, 0),
   # (41, 0),
   # (0, 41),
   # (41, 41),
   # (20, 20),
   # (10, 10),
   # (30, 30),
]
